# Generated by Django 5.0.2 on 2024-02-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='cource',
        ),
    ]
