# Generated by Django 5.0.2 on 2024-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_course_id_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
