# Generated by Django 5.0.2 on 2024-02-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='session_year_id',
            new_name='start',
        ),
    ]
